parameters:
    pim_ui.controller.ajax_option.class: Pim\Bundle\CustomEntityBundle\Controller\AjaxOptionController

services:
    pim_custom_entity.controller:
        class: %pim_custom_entity.controller.class%
        scope: request
        arguments:
            - '@pim_custom_entity.action.factory'
            - '@request'
