custom_entities:
    default:
        class: %pim_custom_entity.configuration.default.class%
        extends: ~
        abstract: true
        actions:
            index:
                service: pim_custom_entity.action.index
            edit:
                service: pim_custom_entity.action.edit
            remove:
                service: pim_custom_entity.action.remove
            create:
                service: pim_custom_entity.action.create
            mass_edit:
                service: pim_custom_entity.action.mass_edit
                enabled: false

    quick_create:
        abstract: true
        actions:
            index:
                quick_create: true
            create:
                service: pim_custom_entity.action.quick_create
