parameters:
    pim_custom_entity.event_listener.datagrid.configure_custom_entity_grid.class: Pim\Bundle\CustomEntityBundle\EventListener\DataGrid\ConfigureCustomEntityGridListener
    pim_custom_entity.event_listener.action.security.class:                       Pim\Bundle\CustomEntityBundle\EventListener\Action\SecurityListener

services:
    pim_custom_entity.event_listener.datagrid.configure_custom_entity_grid:
        class: %pim_custom_entity.event_listener.datagrid.configure_custom_entity_grid.class%
        arguments:
            - @pim_custom_entity.action.factory
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before, method: buildBefore }

    pim_custom_entity.event_listener.action.security:
        class: %pim_custom_entity.event_listener.action.security.class%
        arguments:
            - @oro_security.security_facade
        tags:
            - { name: kernel.event_subscriber }
