parameters:
    pim_custom_entity.extension.pager.custom_entity.class:    Pim\Bundle\CustomEntityBundle\Extension\Pager\CustomEntityPagerExtension
    pim_custom_entity.extension.filter.custom_entity.class:   Pim\Bundle\CustomEntityBundle\Extension\Filter\CustomEntityFilterExtension
    pim_custom_entity.extension.selector.custom_entity.class: Pim\Bundle\CustomEntityBundle\Extension\Selector\CustomEntitySelectorExtension
    pim_custom_entity.extension.sorter.custom_entity.class:   Pim\Bundle\CustomEntityBundle\Extension\Sorter\CustomEntitySorterExtension

services:
    pim_custom_entity.extension.pager.custom_entity:
        parent: pim_datagrid.extension.pager.orm_pager
        class: "%pim_custom_entity.extension.pager.custom_entity.class%"
        tags:
            - { name: oro_datagrid.extension }

    pim_custom_entity.extension.filter.custom_entity:
        parent: pim_datagrid.extension.filter.orm_filter
        class: "%pim_custom_entity.extension.filter.custom_entity.class%"
        tags:
            - { name: oro_datagrid.extension }

    pim_custom_entity.extension.sorter.custom_entity:
        parent: pim_datagrid.extension.sorter.orm_sorter
        class: "%pim_custom_entity.extension.sorter.custom_entity.class%"
        tags:
            - { name: oro_datagrid.extension }
