services:
    pim_custom_entity.form.type.custom_entity:
        class: Pim\Bundle\CustomEntityBundle\Form\Type\CustomEntityType
        tags:
            - { name: form.type, alias: pim_custom_entity }
