parameters:
    pim_custom_entity.job.job_parameters.constraint_collection_provider.reference_data.class: Pim\Bundle\CustomEntityBundle\Connector\Job\JobParameters\ConstraintCollectionProvider\ReferenceData
    pim_custom_entity.job.job_parameters.default_values_provider.reference_data.class:        Pim\Bundle\CustomEntityBundle\Connector\Job\JobParameters\DefaultValuesProvider\ReferenceData
    pim_custom_entity.job.job_parameters.form_configuration_provider.reference_data.class:    Pim\Bundle\CustomEntityBundle\Connector\Job\JobParameters\FormConfigurationProvider\ReferenceData

    pim_custom_entity.job.job_parameters.default_values_provider.quick_csv_export.class:        Pim\Bundle\CustomEntityBundle\MassEditConnector\JobParameters\DefaultValuesProvider\QuickCsvExport
    pim_custom_entity.job.job_parameters.constraint_collection_provider.quick_csv_export.class: Pim\Bundle\CustomEntityBundle\MassEditConnector\JobParameters\ConstraintCollectionProvider\QuickCsvExport

services:
    # Constraints providers
    pim_custom_entity.job.job_parameters.constraint_collection_provider.reference_data_csv_import:
        class: '%pim_custom_entity.job.job_parameters.constraint_collection_provider.reference_data.class%'
        arguments:
            - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_import'
            - '@pim_custom_entity.configuration.registry'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_import%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pim_custom_entity.job.job_parameters.constraint_collection_provider.reference_data_csv_export:
        class: '%pim_custom_entity.job.job_parameters.constraint_collection_provider.reference_data.class%'
        arguments:
            - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export'
            - '@pim_custom_entity.configuration.registry'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    # Form configuration providers
    pim_custom_entity.job.job_parameters.form_configuration_provider.reference_data_csv_import:
        class: '%pim_custom_entity.job.job_parameters.form_configuration_provider.reference_data.class%'
        arguments:
            - '@pim_import_export.job_parameters.form_configuration_provider.simple_csv_import'
            - '@pim_custom_entity.configuration.registry'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_import%'
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }

    pim_custom_entity.job.job_parameters.form_configuration_provider.reference_data_csv_export:
        class: '%pim_custom_entity.job.job_parameters.form_configuration_provider.reference_data.class%'
        arguments:
            - '@pim_import_export.job_parameters.form_configuration_provider.simple_csv_export'
            - '@pim_custom_entity.configuration.registry'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_export%'
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }

    # Default values providers
    pim_custom_entity.job.job_parameters.default_values_provider.reference_data_csv_import:
        class: '%pim_custom_entity.job.job_parameters.default_values_provider.reference_data.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_import'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_import%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_custom_entity.job.job_parameters.default_values_provider.reference_data_csv_export:
        class: '%pim_custom_entity.job.job_parameters.default_values_provider.reference_data.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }


    pim_custom_entity.connector.job.job_parameters.default_values_provider.reference_data_quick_export:
        class: '%pim_custom_entity.job.job_parameters.default_values_provider.quick_csv_export.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_quick_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_custom_entity.connector.job.job_parameters.constraint_collection_provider.reference_data_quick_export:
        class: '%pim_custom_entity.job.job_parameters.constraint_collection_provider.quick_csv_export.class%'
        arguments:
            - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export'
            -
                - '%pim_custom_entity.job_name.csv_reference_data_quick_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
