parameters:
    pim_custom_entity.connector_name.csv: 'Reference data CSV Connector'
    pim_custom_entity.connector_name.xlsx: 'Reference data XLSX Connector'

    pim_custom_entity.job_name.csv_reference_data_import: 'csv_reference_data_import'
    pim_custom_entity.job_name.xlsx_reference_data_import: 'xlsx_reference_data_import'
    pim_custom_entity.job_name.csv_reference_data_export: 'csv_reference_data_export'
    pim_custom_entity.job_name.xlsx_reference_data_export: 'xlsx_reference_data_export'

    pim_custom_entity.job_name.csv_reference_data_quick_export: 'csv_reference_data_quick_export'
    pim_custom_entity.job_name.xlsx_reference_data_quick_export: 'xlsx_reference_data_quick_export'

services:
    # Jobs
    pim_custom_entity.job.csv_reference_data_quick_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_custom_entity.job_name.csv_reference_data_quick_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_custom_entity.step.csv_reference_data_quick_export'
        tags:
            - { name: akeneo_batch.job, connector: '%pim_custom_entity.connector_name.csv%', type: '%pim_enrich.job.quick_export_type%' }

    pim_custom_entity.job.csv_reference_data_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_custom_entity.job_name.csv_reference_data_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@pim_custom_entity.step.csv_reference_data_import'
        tags:
            - { name: akeneo_batch.job, connector: '%pim_custom_entity.connector_name.csv%', type: '%pim_connector.job.import_type%' }

    # Steps
    pim_custom_entity.step.csv_reference_data_import:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - '%pim_connector.job.import_type%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_custom_entity.reader.file.csv'
            - '@pim_custom_entity.processor.denormalization.custom_entity'
            - '@pim_custom_entity.writer.database.custom_entity'

    pim_custom_entity.step.csv_reference_data_quick_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - '%pim_enrich.job.quick_export_type%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_custom_entity.mass_edit_connector.reader.reference_data'
            - '@pim_custom_entity.mass_edit_connector.processor.reference_data_to_flat_array'
            - '@pim_custom_entity.mass_edit_connector.processor.reference_data_writer'
