parameters:
    pim_custom_entity.mass_action.datagrid_query_generator.class: Pim\Bundle\CustomEntityBundle\MassAction\DataGridQueryGenerator
    pim_custom_entity.mass_action.mass_updater.class:             Pim\Bundle\CustomEntityBundle\MassAction\MassUpdater

services:
    pim_custom_entity.mass_action.datagrid_query_generator:
        class: %pim_custom_entity.mass_action.datagrid_query_generator.class%
        arguments:
            - '@oro_datagrid.datagrid.manager'
            - '@oro_datagrid.datagrid.request_params'
            - '@oro_datagrid.mass_action.parameters_parser'

    pim_custom_entity.mass_action.mass_updater:
        class: %pim_custom_entity.mass_action.mass_updater.class%
        arguments:
            - '@doctrine'
