parameters:
    pim_custom_entity.mass_action.datagrid_query_generator.class: Pim\Bundle\CustomEntityBundle\MassAction\DataGridQueryGenerator
    pim_custom_entity.mass_action.mass_updater.class:             Pim\Bundle\CustomEntityBundle\MassAction\MassUpdater

services:
    pim_custom_entity.mass_action.datagrid_query_generator:
        class: %pim_custom_entity.mass_action.datagrid_query_generator.class%
        arguments:
            - '@oro_datagrid.datagrid.manager'
            - '@oro_datagrid.datagrid.request_params'
            - '@oro_datagrid.mass_action.parameters_parser'

    pim_custom_entity.mass_action.mass_updater:
        class: %pim_custom_entity.mass_action.mass_updater.class%
        arguments:
            - '@doctrine'

    pim_custom_entity.mass_action.mass_action.handler.edit:
        class: %pim_datagrid.extension.mass_action.handler.edit.class%
        arguments:
            - '@pim_datagrid.datasource.result_record.hydrator.object_id'
            - '@event_dispatcher'
        tags:
            - { name: pim_datagrid.extension.mass_action.handler, alias: custom_mass_edit }
