parameters:
    pim_custom_entity.mass_edit_connector.reader.reference_data.class: Pim\Bundle\CustomEntityBundle\MassEditConnector\Reader\ReferenceDataReader

services:
    pim_custom_entity.mass_edit_connector.reader.reference_data:
        class: %pim_custom_entity.mass_edit_connector.reader.reference_data.class%
        arguments:
            - '@pim_connector.repository.job_configuration'
            - '@doctrine.orm.entity_manager'
