pim_customentity_index:
    path: /{customEntityName}/.{_format}
    defaults: { _controller: pim_customentity.controller:executeAction, _format: html, actionType: index }
    requirements:
        _format: html|json|csv

pim_customentity_create:
    path: /{customEntityName}/create
    defaults: { _controller: pim_customentity.controller:executeAction, actionType: create }

pim_customentity_massedit:
    path: /{customEntityName}/mass-edit
    defaults: { _controller: pim_customentity.controller:executeAction, actionType: mass_edit }

pim_customentity_edit:
    path: /{customEntityName}/{id}/edit
    defaults: { _controller: pim_customentity.controller:executeAction, actionType: edit }
    requirements:
        id: \d+

pim_customentity_delete:
    path: /{customEntityName}/{id}/delete
    defaults: { _controller: pim_customentity.controller:executeAction, actionType: delete }
    requirements:
        id: \d+
    methods: [DELETE, POST]
