parameters:
    pim_custom_entity.normalizer.referable.class:         Pim\Bundle\CustomEntityBundle\Normalizer\ReferableNormalizer

services:
    pim_custom_entity.normalizer.referable:
        class: %pim_custom_entity.normalizer.referable.class%
        arguments:
            - ['csv', 'flat']
        tags:
            - { name: pim_versioning.serializer.normalizer, priority: 100 }
            - { name: pim_serializer.normalizer, priority: 100 }
