parameters:
    pim_custom_entity.configuration.registry.class:                Pim\Bundle\CustomEntityBundle\Configuration\Registry
    pim_custom_entity.configuration.default.class:                 Pim\Bundle\CustomEntityBundle\Configuration\Configuration
    pim_custom_entity.controller.class:                            Pim\Bundle\CustomEntityBundle\Controller\Controller
    pim_custom_entity.manager.orm.class:                           Pim\Bundle\CustomEntityBundle\Manager\OrmManager

services:
    pim_custom_entity.configuration.registry:
        class: %pim_custom_entity.configuration.registry.class%

    pim_custom_entity.controller:
        class: %pim_custom_entity.controller.class%
        scope: request
        arguments:
            - '@request'
            - '@pim_custom_entity.configuration.registry'

    pim_custom_entity.manager.orm:
        class: %pim_custom_entity.manager.orm.class%
        arguments:
            - '@doctrine'
            - '@property_accessor'
