language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"

# Allow to use container infrastructure
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
    - phpenv config-add travis.php.ini
    - composer self-update --no-interaction

install:
    - composer update --no-interaction --no-scripts

script:
    - bin/phpspec run -f dot

notifications:
    slack: akeneo:RtMZyFyncKFKYKFT3kdzLvid
