language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"

cache:
    directories:
        - vendor

before_script:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction
    - composer update --prefer-source

script:
    - ./bin/phpspec run

notifications:
    slack: akeneo:RtMZyFyncKFKYKFT3kdzLvid
