language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"

# Allow to use container infrastructure
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.4
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 5.6
          env: DEPENDENCIES=dev

before_install:
    - phpenv config-add travis.php.ini
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
    - composer update $COMPOSER_FLAGS

script:
    - bin/phpspec run -f dot

notifications:
    slack: akeneo:RtMZyFyncKFKYKFT3kdzLvid
