language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"

# Allow to use container infrastructure
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - phpenv config-add travis.php.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./bin/phpspec run

notifications:
    slack: akeneo:RtMZyFyncKFKYKFT3kdzLvid
